"""Tests of the report generated by the graphical interface (Ctrl+R)."""

import os
import tempfile
import unittest
import unittest.mock

from asmx.logging_setup import reset_logging

try:
    import tkinter as tk

    TK_OK = True
except ImportError:  # pragma: no cover
    TK_OK = False

HAS_DISPLAY = bool(os.environ.get("DISPLAY")) or os.name == "nt"


@unittest.skipUnless(TK_OK and HAS_DISPLAY, "no Tkinter or no display")
class TestReportInTheInterface(unittest.TestCase):
    """The "Generate report..." menu item must work end to end."""

    @classmethod
    def setUpClass(cls) -> None:
        """Load the application class once for the whole test case."""
        from asmx.ui.app import AsmXApp

        cls.AsmXApp = AsmXApp

    def setUp(self) -> None:
        """Open a window with a temporary folder for the report."""
        self.dir = tempfile.TemporaryDirectory()
        self.app = self.AsmXApp()
        self.app.update()

    def tearDown(self) -> None:
        """Destroy the window and clean the temporary folder."""
        try:
            self.app.destroy()
        except tk.TclError:
            pass
        self.dir.cleanup()
        reset_logging()

    def destination(self, name: str = "rel.html") -> str:
        """Return the path of a report inside the temporary folder.

        Returns:
            Path of the report inside the temporary folder of the test.
        """
        return os.path.join(self.dir.name, name)

    def test_generates_html_and_opens_in_browser(self) -> None:
        """The generated HTML opens in the browser and updates the status line."""
        path = self.destination()
        with (
            unittest.mock.patch("asmx.ui.app.filedialog.asksaveasfilename", return_value=path),
            unittest.mock.patch("asmx.ui.app.webbrowser.open") as opened,
        ):
            self.app.generate_report()
        self.assertTrue(os.path.exists(path))
        with open(path, encoding="utf-8") as handle:
            content = handle.read()
        self.assertIn("<!DOCTYPE html>", content)
        self.assertIn("ASM X", content)
        self.assertIn("Hello, world!", content)
        opened.assert_called_once()
        self.assertIn("report written to", self.app.status.cget("text"))

    def test_cancelling_writes_nothing(self) -> None:
        """Cancelling the dialog writes no file and opens nothing."""
        with (
            unittest.mock.patch("asmx.ui.app.filedialog.asksaveasfilename", return_value=""),
            unittest.mock.patch("asmx.ui.app.webbrowser.open") as opened,
        ):
            self.app.generate_report()
        self.assertEqual(os.listdir(self.dir.name), [])
        opened.assert_not_called()

    def test_write_error_warns_without_crashing(self) -> None:
        """A write error shows a message and keeps the window alive."""
        with (
            unittest.mock.patch(
                "asmx.ui.app.filedialog.asksaveasfilename", return_value=self.dir.name
            ),
            unittest.mock.patch("asmx.ui.app.messagebox.showerror") as error,
            unittest.mock.patch("asmx.ui.app.webbrowser.open") as opened,
        ):
            self.app.generate_report()
        error.assert_called_once()
        opened.assert_not_called()
        self.assertTrue(self.app.winfo_exists())

    def test_menu_has_generate_report_with_accelerator(self) -> None:
        """The Run menu carries the report item with the Ctrl+R accelerator."""
        bar = self.app.nametowidget(self.app.cget("menu"))
        items = []
        for index in range(bar.index("end") + 1):
            if bar.type(index) != "cascade":
                continue
            cascade = bar.entrycget(index, "label")
            submenu = self.app.nametowidget(bar.entrycget(index, "menu"))
            for position in range(submenu.index("end") + 1):
                if submenu.type(position) != "command":
                    continue
                try:
                    accelerator = submenu.entrycget(position, "accelerator")
                except tk.TclError:
                    accelerator = ""
                items.append((cascade, submenu.entrycget(position, "label"), accelerator))
        self.assertIn(("Run", "Generate report...", "Ctrl+R"), items)

    def test_report_uses_the_current_editor_code(self) -> None:
        """The report reflects the code that is in the editor."""
        self.app.editor.set_code('section .data\nmsg db "INTERESTING", 0\n')
        self.app.on_code_change()
        path = self.destination("current.html")
        with (
            unittest.mock.patch("asmx.ui.app.filedialog.asksaveasfilename", return_value=path),
            unittest.mock.patch("asmx.ui.app.webbrowser.open"),
        ):
            self.app.generate_report()
        with open(path, encoding="utf-8") as handle:
            self.assertIn("INTERESTING", handle.read())


if __name__ == "__main__":
    unittest.main()
